### PR TITLE
Change the plugin vendor from KK to jenkins organization

### PR DESCRIPTION
**Pull request by duemir**
This should enable plugin transfer as per [Plugin transfer](https://plugins.jetbrains.com/docs/marketplace/organizations.html#plugin-transfer) doc.  Which then enable more contributors to upload new version.

### CODE REVIEW

**Comment by duemir** [comment]
@oleg-nenashev @kohsuke this the change that needs to happen in the plugin as far as I understand the doc.

**Review by oleg-nenashev — APPROVED** [review]
Jenkins community and a link to jenkons.io? Maybe we should also register Stapler as a subproject 8n Jenkins. It is rather a legacy one, but IMHO it qualifies

**Comment by duemir** [comment]
Jenkins community and a link to jenkons.io? 
JetBrains does not bother to do it but they probably rely on the defaults. The values appear to be used in the plugin manager and on the error reporting dialog. What URL and email are best to add?

**Comment by oleg-nenashev** [comment]
I was about creating a Stapler subproject page based on the devlist conversation. https://jenkins.io/projects/stapler when created, I believe. Or maybe it is better to move the project to jenkinsci and link the github repo.

No idea about email. Maybe default to the devlist for now?

**Comment by duemir** [comment]
> Or maybe it is better to move the project to jenkinsci and link the github repo.
>No idea about email. Maybe default to the devlist for now?

I am only vague about where these will show up. Most likely most prominently they'll show up on the crash report form. ATM, I added the values as you suggested.

**Comment by duemir** [comment]
As discussed in chat. I've changed the Vendor URL to this new repo. Merging it as final.

**Pull request merged**
