### PR TITLE
Update minimum version to 2023.3

### PR DESCRIPTION
**Pull request by timja**
Part of https://github.com/jenkinsci/idea-stapler-plugin/issues/189

This version was released in February 2024 which I think is plenty of time. People will still get old versions if they haven't updated so I don't see why we would need to be too conservative, i.e. there's a feature we want which is beneficial lets just update the min, any other thoughts against this?

### Testing done

Ran `./gradlew runIde` tried out stapler auto completion and clicked around a bit.

### Submitter checklist
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by duemir** [comment]
I never defined an explicit "policy". #15 was created to do it. https://plugins.jetbrains.com/docs/marketplace/product-versions-in-use-statistics.html is the relevant doc.

The implicit policy that I've been following is bumping the `ideaVersion` property by one year around January every year.

**Comment by timja** [comment]
Unfortunately that doc isn’t that useful as the data is nearly a year out of date.

this is a similar question to https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/

and generally we recommend if there’s a good reason to increase it to just do it as previous versions will be around, and if you really need to you can always do a backport release for older versions

**Comment by timja** [comment]
This is the third version line ago which should cover most people:
https://www.jetbrains.com/idea/download/other.html

**Comment by timja** [comment]
@duemir think we could go ahead with this?

**Pull request merged**
