### PR TITLE
Add support for groovy views as well as help files in the structure view

### PR DESCRIPTION
**Pull request by Vlatombe**
- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by duemir** [comment]
I think it is a good idea to compare the File Type, but I think it'll be better to keep it typesafe and compare it with `FileType` instances. I'll doodle a bit to figure out the approach.
Maybe I am overthinking it, but I want to add a Groovy plugin as an optional dependency.

**Comment by duemir** [comment]
I made it work which made me realise that it'll lead to groovy views showing up only when Groovy plugin is installed. So this should probably be just right. Maybe using file extensions will make it closer to stapler itself 🤔

**Comment by duemir** [comment]
Well, this implementation doesn't work if the Groovy plugin is not installed. Without the plugin, there is no "Groovy" file type.

**Comment by duemir** [comment]
#153 is my rough idea of how to do it via the Extension Point.

**Comment by duemir** [comment]
@timja can you give your two cents?

**Comment by timja** [comment]
Does this assume all groovy files could be views?

----

No strong opinions on this, generally I convert groovy views to jelly if I have to do anything nontrivial on them.
We don't really recommend groovy views for new code.

**Comment by duemir** [comment]
> Does this assume all groovy files could be views?
> 

All groovy files in a package that has the same name as fully qualified name of a class for which structure view is constructed

**Comment by timja** [comment]
> > Does this assume all groovy files could be views?
> 
> All groovy files in a package that has the same name as fully qualified name of a class for which structure view is constructed

ok so sounds safe enough

**Review by duemir — APPROVED** [review]

**Pull request merged**
